development:
  adapter: postgresql
  encoding: unicode
  database: sonu_app_dev
  pool: 5
  username: ghanshyam
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sonu_app_test
  pool: 5
  username: ghanshyam
  password:
